### PR TITLE
Octave kernel

### PR DESCRIPTION
**Pull request by diocas**
Added option to show Octave kernel.
Prevents kernels from CVMFS to show automatically.

### CODE REVIEW

**Comment by diocas** [comment]
@etejedor 
Before merging, please wait for the Octave_Kernel PR to be approved.

**Comment by diocas** [comment]
Ok, it looks like it was merged in the octave_kernel. But let's wait to see if adding the gnuplot to CVFMS is straightforward..

**Comment by diocas** [comment]
@etejedor 
I would say that is ready to be approved

**Comment by etejedor** [comment]
Please see my e-mail, I believe the kernel does not fully work yet. I tried to run the notebook here:
https://github.com/Calysto/octave_kernel
without success.

**Comment by etejedor** [comment]
Isn't there code overlap between this PR and the newer one (#8)?

**Comment by diocas** [comment]
The #8 is a backport of the octave kernel to v2.x. This is the original PR to add Octave in v3.x.

**Pull request merged**
